#You need to get a TOKEN talking to the @botfather bot 
# as [described here](https://core.telegram.org/bots#6-botfather). 
# Remember you can use the [Telegram web client](https://web.telegram.org/), 
# although you still need a phone with telegram to allow connecting to it.

telegram:
  token: "258802481:AAFu1mTCr4b0KT8uX_ls9T1cFGiwR6QiQ_N"